---
# Rules https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md
default: true
list-marker-space: false
line-length: false
MD004:
  style: dash
MD003:
  style: atx
MD007:
  indent: 2
MD024:
  allow_different_nesting: true
MD033:
  allowed_elements:
  - pre
