version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - run:
          name: "Install markdownlint-cli"
          command: |
              sudo npm install -g markdownlint-cli
      - run:
          name: "Check with markdownlint"
          command: |
              echo -n "markdownlint version: "
              markdownlint --version
              markdownlint ./
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
